### PR TITLE
Adding Dockerfile to run examples

### LINKED ISSUE #5: Provide container for easier interaction
It would be good to have a Dockerfile that can quickly be built and spin up a container with all the dependencies to run the examples.

Please assign this to me!

### PR DESCRIPTION
**Pull request by vsoch**
This PR adds a Dockerfile that a developer/user can build to quickly interact with examples. The container includes a jupyter-minimal notebook with database and python dependencies for the project. Note that it looks like I need a database password to run most examples so I didn't test them all the way through. I also tweaked the README to include instructions to build and run the container, and re-organized the getting started a bit so there are clear sections for install, notebooks, and the container.

This will close #5

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by brnorris03** [comment]
Can you test with the password "cabbage"? Thank you!!!

**Comment by vsoch** [comment]
haha that's one of my favorite vegetables! I'm testing notebooks/PatternsTest.ipynb and it looks like there is a spack data file missing called `.db-cache/.spack.pickle`?

image

**Comment by brnorris03** [comment]
It should have created it the first time it got the data from the database. What do you see in the .db-cache directory? 

Also, please remove everything in .db-cache and run again -- you do have to provide the password again in that case. Let me know what you observe. I will try to reproduce.

**Comment by brnorris03** [comment]
Actually, I think the issue is the path -- it's missing the prefix!

**Comment by vsoch** [comment]
Ah gotcha! Let me see if I can find the file in the container and then adjust the path.

**Comment by vsoch** [comment]
Here is printing that line, and then printing the `self.top_dir` in fetcher.py:

```python
print(self.top_dir)
/code

print(abspath(__file__))
/code/src/patterns/fetcher.py
```

**Comment by brnorris03** [comment]
Okay, so the path is not incorrect. The other thing to rule out is running the test from the wrong location. Notebooks are particularly finicky w.r.t. that. Are you running the tests in the top-level repo directory with: `python -m pytest -v` ?

**Comment by vsoch** [comment]
No, I'm running it from the interactive notebook container, so it's in my browser.

**Comment by vsoch** [comment]
That test command seems okay from the same root in the container (but there are a few warnings):

```bash
$ python -m pytest -v
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /code, configfile: pytest.ini, testpaths: src/gitutils/tests, src/patterns/tests
plugins: anyio-3.2.1
collected 4 items                                                                                                                                                         

src/gitutils/tests/test_cloneRepo.py ..                                                                                                                             [ 50%]
src/patterns/tests/test_01_instantiateVisualizer.py .                                                                                                               [ 75%]
src/patterns/tests/test_readCachedProject.py .                                                                                                                      [100%]

============================================================================ warnings summary =============================================================================
../opt/conda/lib/python3.9/site-packages/_pytest/cacheprovider.py:428
  /opt/conda/lib/python3.9/site-packages/_pytest/cacheprovider.py:428: PytestCacheWarning: could not create cache path /code/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../opt/conda/lib/python3.9/site-packages/_pytest/stepwise.py:49
  /opt/conda/lib/python3.9/site-packages/_pytest/stepwise.py:49: PytestCacheWarning: could not create cache path /code/.pytest_cache/v/cache/stepwise
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/warnings.html
===================================================================== 4 passed, 2 warnings in 12.12s ======================================================================
```

**Comment by brnorris03** [comment]
In which directory did you start the jupyter server?

**Comment by vsoch** [comment]
Okay so I just tested having the software installed from and then run from the same location (/home/jovyan/work) assuming that was the issue - but the error persists, this time just telling me it doesn't find the same file in jovyan's work folder. I also went to the root of the container:

```
$ find . -name "*.pickle"
./home/jovyan/work/src/patterns/tests/.testrepo.pickle
./opt/conda/lib/python3.9/lib2to3/Grammar3.9.5.final.0.pickle
./opt/conda/lib/python3.9/lib2to3/PatternGrammar3.9.5.final.0.pickle
```
And that file absolutely does not exist in the container, anywhere. So I don't think this is a path issue, but an issue that the file isn't being produced at all?

**Comment by brnorris03** [comment]
Right, actually I should have noticed this earlier, but the error is happening while you are trying to create the cached database file. It's not able to **write** the file out because it's trying to write to the `/code/.db-cache` directory, which either doesn't exist or is not writeable. I need to add more checks for that, but in the meanwhile, create the `/code/.db-cache` manually and see if you get past this issue. The `.spack.pickle` file should appear there the first time you download the data from the database. 

Also, run the `jupyter notebook ` from the notebooks subirectory.

I think the caching issue can be considered a bug... It is easy to make the directory if it doesn't exist. I'll fix. The jupyter notebook would always have to be run  in its local directory, but I think that's minor.

**Comment by vsoch** [comment]
Ah gotcha, I totally missed that! I can add a fix to this PR.

**Comment by vsoch** [comment]
okay almost got it working! Where should the "figures" directory be generated?

**Comment by brnorris03** [comment]
Depends on whether running the notebook or not; I think I'll just add the figures directories (not files) to the repo so this will not be an issue in future, but here they are: 
```
./sandbox/figures
./figures
./notebooks/figures
```

**Comment by brnorris03** [comment]
Actually, the visualizer is already supposed to create the figures subdirectory as needed...

**Comment by vsoch** [comment]
That's why I was asking - I saw this line:

> if not os.path.exists('figures'): os.mkdir('figures')

And I wanted to double check the context of that.

**Comment by vsoch** [comment]
okay all fixed! These plots are gorgeous! :heart_eyes: 

image

**Comment by brnorris03** [comment]
Okay, commit made to `master` (need to rename to main, but will do after we merge). Tested everything on a fresh clone, following README instructions and observed no pickle or figure problems with multiple runs.  This happens to be Ubuntu.
```sudo apt install libmysqlclient-dev
pip install -r requirements.txt
pip install -e .
jupyter notebook notebooks/PatternsTest.ipynb
```

Pytest in top dir:
```python3 -m pytest . -v
===================================================================== test session starts ======================================================================
platform linux -- Python 3.8.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /disks/large/home/users/norris/research/ideas-uo, configfile: pytest.ini
collected 6 items                                                                                                                                              

notebooks/tests/test_PatternsTest_ipynb.py .[I 12:58:46.777 NotebookApp] Saving file at /PatternsTest.ipynb
.                                                                                                            [ 33%]
src/gitutils/tests/test_cloneRepo.py ..                                                                                                                  [ 66%]
src/patterns/tests/test_01_instantiateVisualizer.py .                                                                                                    [ 83%]
src/patterns/tests/test_readCachedProject.py .                                                                                                           [100%]

================================================================= 6 passed in 90.25s (0:01:30) =================================================================

**Comment by brnorris03** [comment]
Just saw you got it to work!! Woohoo! Thank you for all your patience and work on this!

**Pull request merged**
